create type "public"."user_role" as enum ('user', 'admin');


  create table "public"."brands" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying
      );


alter table "public"."brands" enable row level security;


  create table "public"."movies" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp without time zone default now(),
    "name" character varying,
    "movie_img" character varying,
    "director" character varying,
    "duration" integer,
    "genre" character varying,
    "movie_status" character varying
      );


alter table "public"."movies" enable row level security;


  create table "public"."profile" (
    "user_id" uuid not null,
    "role" public.user_role not null default 'user'::public.user_role,
    "first_name" character varying,
    "last_name" character varying,
    "email" character varying,
    "mobile_no" bigint,
    "age" character varying,
    "address" character varying,
    "created_at" timestamp with time zone default now(),
    "updated_at" timestamp with time zone default now()
      );


alter table "public"."profile" enable row level security;


  create table "public"."theater" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "updated_at" timestamp with time zone default now(),
    "name" character varying,
    "address" json
      );


alter table "public"."theater" enable row level security;

CREATE UNIQUE INDEX brands_pkey ON public.brands USING btree (id);

CREATE UNIQUE INDEX profile_pkey ON public.profile USING btree (user_id);

CREATE UNIQUE INDEX theater_pkey ON public.theater USING btree (id);

alter table "public"."brands" add constraint "brands_pkey" PRIMARY KEY using index "brands_pkey";

alter table "public"."profile" add constraint "profile_pkey" PRIMARY KEY using index "profile_pkey";

alter table "public"."theater" add constraint "theater_pkey" PRIMARY KEY using index "theater_pkey";

alter table "public"."profile" add constraint "profile_user_id_fkey" FOREIGN KEY (user_id) REFERENCES auth.users(id) ON DELETE CASCADE not valid;

alter table "public"."profile" validate constraint "profile_user_id_fkey";

set check_function_bodies = off;

CREATE OR REPLACE FUNCTION public.handle_new_user()
 RETURNS trigger
 LANGUAGE plpgsql
 SECURITY DEFINER
 SET search_path TO 'public'
AS $function$
BEGIN
  INSERT INTO public.profile (
    user_id,
    role,
    first_name,
    last_name,
    email,
    mobile_no,
    age,
    address,
    created_at,
    updated_at
  )
  VALUES (
    NEW.id,                                      -- maps auth.id → profile.user_id
    'user',                                      -- default role (change as needed)
    NEW.raw_user_meta_data->>'first_name',   
    null,      -- from auth metadata
    NEW.email,                                   -- from auth.users
    NULL,                                        -- mobile_no (set later by user)
    NULL,                                        -- age (set later by user)
    NULL,                                        -- address (set later by user)
    NOW(),
    NOW()
  );
  RETURN NEW;
END;
$function$
;

grant delete on table "public"."brands" to "anon";

grant insert on table "public"."brands" to "anon";

grant references on table "public"."brands" to "anon";

grant select on table "public"."brands" to "anon";

grant trigger on table "public"."brands" to "anon";

grant truncate on table "public"."brands" to "anon";

grant update on table "public"."brands" to "anon";

grant delete on table "public"."brands" to "authenticated";

grant insert on table "public"."brands" to "authenticated";

grant references on table "public"."brands" to "authenticated";

grant select on table "public"."brands" to "authenticated";

grant trigger on table "public"."brands" to "authenticated";

grant truncate on table "public"."brands" to "authenticated";

grant update on table "public"."brands" to "authenticated";

grant delete on table "public"."brands" to "service_role";

grant insert on table "public"."brands" to "service_role";

grant references on table "public"."brands" to "service_role";

grant select on table "public"."brands" to "service_role";

grant trigger on table "public"."brands" to "service_role";

grant truncate on table "public"."brands" to "service_role";

grant update on table "public"."brands" to "service_role";

grant delete on table "public"."movies" to "anon";

grant insert on table "public"."movies" to "anon";

grant references on table "public"."movies" to "anon";

grant select on table "public"."movies" to "anon";

grant trigger on table "public"."movies" to "anon";

grant truncate on table "public"."movies" to "anon";

grant update on table "public"."movies" to "anon";

grant delete on table "public"."movies" to "authenticated";

grant insert on table "public"."movies" to "authenticated";

grant references on table "public"."movies" to "authenticated";

grant select on table "public"."movies" to "authenticated";

grant trigger on table "public"."movies" to "authenticated";

grant truncate on table "public"."movies" to "authenticated";

grant update on table "public"."movies" to "authenticated";

grant delete on table "public"."movies" to "service_role";

grant insert on table "public"."movies" to "service_role";

grant references on table "public"."movies" to "service_role";

grant select on table "public"."movies" to "service_role";

grant trigger on table "public"."movies" to "service_role";

grant truncate on table "public"."movies" to "service_role";

grant update on table "public"."movies" to "service_role";

grant delete on table "public"."profile" to "anon";

grant insert on table "public"."profile" to "anon";

grant references on table "public"."profile" to "anon";

grant select on table "public"."profile" to "anon";

grant trigger on table "public"."profile" to "anon";

grant truncate on table "public"."profile" to "anon";

grant update on table "public"."profile" to "anon";

grant delete on table "public"."profile" to "authenticated";

grant insert on table "public"."profile" to "authenticated";

grant references on table "public"."profile" to "authenticated";

grant select on table "public"."profile" to "authenticated";

grant trigger on table "public"."profile" to "authenticated";

grant truncate on table "public"."profile" to "authenticated";

grant update on table "public"."profile" to "authenticated";

grant delete on table "public"."profile" to "service_role";

grant insert on table "public"."profile" to "service_role";

grant references on table "public"."profile" to "service_role";

grant select on table "public"."profile" to "service_role";

grant trigger on table "public"."profile" to "service_role";

grant truncate on table "public"."profile" to "service_role";

grant update on table "public"."profile" to "service_role";

grant delete on table "public"."theater" to "anon";

grant insert on table "public"."theater" to "anon";

grant references on table "public"."theater" to "anon";

grant select on table "public"."theater" to "anon";

grant trigger on table "public"."theater" to "anon";

grant truncate on table "public"."theater" to "anon";

grant update on table "public"."theater" to "anon";

grant delete on table "public"."theater" to "authenticated";

grant insert on table "public"."theater" to "authenticated";

grant references on table "public"."theater" to "authenticated";

grant select on table "public"."theater" to "authenticated";

grant trigger on table "public"."theater" to "authenticated";

grant truncate on table "public"."theater" to "authenticated";

grant update on table "public"."theater" to "authenticated";

grant delete on table "public"."theater" to "service_role";

grant insert on table "public"."theater" to "service_role";

grant references on table "public"."theater" to "service_role";

grant select on table "public"."theater" to "service_role";

grant trigger on table "public"."theater" to "service_role";

grant truncate on table "public"."theater" to "service_role";

grant update on table "public"."theater" to "service_role";


  create policy "Service role can insert profile"
  on "public"."profile"
  as permissive
  for insert
  to public
with check (true);



  create policy "Users can update own profile"
  on "public"."profile"
  as permissive
  for update
  to public
using ((auth.uid() = user_id));



  create policy "Users can view own profile"
  on "public"."profile"
  as permissive
  for select
  to public
using ((auth.uid() = user_id));


CREATE TRIGGER on_auth_user_created AFTER INSERT ON auth.users FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();


