drop extension if exists "pg_net";


  create table "public"."blog" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "type" character varying,
    "title" character varying,
    "imageUrl" character varying,
    "videoUrl" character varying,
    "description" character varying,
    "likes" bigint not null default '0'::bigint
      );



  create table "public"."todos" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "todo" text
      );


CREATE UNIQUE INDEX blog_pkey ON public.blog USING btree (id);

CREATE UNIQUE INDEX todo_pkey ON public.todos USING btree (id);

alter table "public"."blog" add constraint "blog_pkey" PRIMARY KEY using index "blog_pkey";

alter table "public"."todos" add constraint "todo_pkey" PRIMARY KEY using index "todo_pkey";

grant delete on table "public"."blog" to "anon";

grant insert on table "public"."blog" to "anon";

grant references on table "public"."blog" to "anon";

grant select on table "public"."blog" to "anon";

grant trigger on table "public"."blog" to "anon";

grant truncate on table "public"."blog" to "anon";

grant update on table "public"."blog" to "anon";

grant delete on table "public"."blog" to "authenticated";

grant insert on table "public"."blog" to "authenticated";

grant references on table "public"."blog" to "authenticated";

grant select on table "public"."blog" to "authenticated";

grant trigger on table "public"."blog" to "authenticated";

grant truncate on table "public"."blog" to "authenticated";

grant update on table "public"."blog" to "authenticated";

grant delete on table "public"."blog" to "service_role";

grant insert on table "public"."blog" to "service_role";

grant references on table "public"."blog" to "service_role";

grant select on table "public"."blog" to "service_role";

grant trigger on table "public"."blog" to "service_role";

grant truncate on table "public"."blog" to "service_role";

grant update on table "public"."blog" to "service_role";

grant delete on table "public"."todos" to "anon";

grant insert on table "public"."todos" to "anon";

grant references on table "public"."todos" to "anon";

grant select on table "public"."todos" to "anon";

grant trigger on table "public"."todos" to "anon";

grant truncate on table "public"."todos" to "anon";

grant update on table "public"."todos" to "anon";

grant delete on table "public"."todos" to "authenticated";

grant insert on table "public"."todos" to "authenticated";

grant references on table "public"."todos" to "authenticated";

grant select on table "public"."todos" to "authenticated";

grant trigger on table "public"."todos" to "authenticated";

grant truncate on table "public"."todos" to "authenticated";

grant update on table "public"."todos" to "authenticated";

grant delete on table "public"."todos" to "service_role";

grant insert on table "public"."todos" to "service_role";

grant references on table "public"."todos" to "service_role";

grant select on table "public"."todos" to "service_role";

grant trigger on table "public"."todos" to "service_role";

grant truncate on table "public"."todos" to "service_role";

grant update on table "public"."todos" to "service_role";


  create policy "anyone can add and see g5al2f_0"
  on "storage"."objects"
  as permissive
  for insert
  to anon
with check ((bucket_id = 'blog_data'::text));



  create policy "anyone can add and see g5al2f_1"
  on "storage"."objects"
  as permissive
  for select
  to anon
using ((bucket_id = 'blog_data'::text));



